/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/File.java to edit this template
 */
package dao;

import entities.Collaborateur;
import entities.Partenaire;
import entities.Prestation;
import entities.ResponsableActivite;
import historique.CSVUtil;
import historique.JsonUtil;
import static historique.JsonUtil.collaborateurToJson;
import static historique.JsonUtil.prestationToJson;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Implementation d'une DAO Gestion du CRUD sur les objets Prestation dans la
 * base de données relationnelles Connexion a la BDD Constructeur Methodes CRUD
 * Gestion des exceptions Methodes specifiques La classe PrestationDao encapsule
 * la logique d'accès aux données pour les objets Prestation
 *
 * @author cberge
 */
public class PrestationDao extends Dao<Prestation> {

    public PrestationDao() {
        super("Prestation");
    }

    /**
     * Crée un objet Prestation à partir des données extraites d'un ResultSet.
     *
     * @param rs le ResultSet contenant les données de la base de données
     * @return un objet Prestation initialisé avec les données du ResultSet
     * @throws SQLException si une erreur survient lors de l'accès aux données
     * du ResultSet
     */
    @Override
    protected Prestation createObject(ResultSet rs) throws SQLException {
        Prestation prestation = new Prestation() {
        };
        prestation.setId(rs.getInt("id_" + table));
        prestation.setSiglum_presta(rs.getString("siglum_presta"));
        prestation.setNum_affaire(rs.getString("num_affaire"));
        prestation.setNom_presta(rs.getString("nom_presta"));
        prestation.setRef_fact_partenaire(rs.getString("ref_fact_partenaire"));
        prestation.setMail_partenaire(rs.getString("mail_partenaire"));
        prestation.setRef_fact_airbus(rs.getString("ref_fact_airbus"));
        prestation.setMail_airbus(rs.getString("mail_airbus"));
        prestation.setId_ra(rs.getInt("id_ra"));
        prestation.setId_collaborateur(rs.getInt("id_collaborateur"));
        prestation.setId_partenaire(rs.getInt("id_partenaire"));

        return prestation;
    }

    /**
     * Crée une nouvelle prestation dans la base de données à partir des
     * informations fournies.
     *
     * @param presta la prestation à créer dans la base de données
     * @throws SQLException si une erreur survient lors de l'insertion dans la
     * base de données
     */
    @Override
    public void create(Prestation presta) throws SQLException {
        String sql = "INSERT INTO prestation(siglum_presta, num_affaire, nom_presta, ref_fact_partenaire, mail_partenaire,"
                + "ref_fact_airbus, mail_airbus, id_ra, id_collaborateur, id_partenaire) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (PreparedStatement pstmt = connexion.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)) {
            pstmt.setString(1, presta.getSiglum_presta());
            pstmt.setString(2, presta.getNum_affaire());
            pstmt.setString(3, presta.getNom_presta());
            pstmt.setString(4, presta.getRef_fact_partenaire());
            pstmt.setString(5, presta.getMail_partenaire());
            pstmt.setString(6, presta.getRef_fact_airbus());
            pstmt.setString(7, presta.getMail_airbus());
            pstmt.setObject(8, presta.getId_ra(), Types.INTEGER);
            pstmt.setObject(9, presta.getId_collaborateur(), Types.INTEGER);
            pstmt.setObject(10, presta.getId_partenaire(), Types.INTEGER);

            int nbLines = pstmt.executeUpdate();
            if (nbLines == 1) {
                ResultSet autoGeneratedKeys = pstmt.getGeneratedKeys();
                autoGeneratedKeys.first();
                int id = autoGeneratedKeys.getInt(1);
                presta.setId(id);
                System.out.println("Responsable d'activité créé avec succès!");
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de l'insertion : " + ex.getMessage());
            throw ex;
        }
    }

    /**
     * Lit et retourne une prestation à partir de la base de données en fonction
     * de son identifiant.
     *
     * @param id l'identifiant de la prestation à lire
     * @return la prestation correspondant à l'identifiant spécifié, ou null si
     * aucune prestation n'est trouvée
     */
    @Override
    public Prestation read(Integer id) {
        Prestation obj = null;
        String sql = "SELECT * FROM prestation WHERE id_prestation=?";
        PreparedStatement pstmt;
        try {
            pstmt = connexion.prepareStatement(sql);
            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();
            if (rs.first()) {
                obj = new Prestation();
                obj.setId(rs.getInt("id_prestation"));
                obj.setSiglum_presta(rs.getString("siglum_presta"));
                obj.setNum_affaire(rs.getString("num_affaire"));
                obj.setNom_presta(rs.getString("nom_presta"));
                obj.setRef_fact_partenaire(rs.getString("ref_fact_partenaire"));
                obj.setMail_partenaire(rs.getString("mail_partenaire"));
                obj.setRef_fact_airbus(rs.getString("ref_fact_airbus"));
                obj.setMail_airbus(rs.getString("mail_airbus"));
                obj.setId_ra(rs.getInt("id_ra"));
                obj.setId_collaborateur(rs.getInt("id_collaborateur"));
                obj.setId_partenaire(rs.getInt("id_partenaire"));
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de la lecture : " + ex.getMessage());
        }
        return obj;
    }

    /**
     * Met à jour les relations entre une prestation et ses partenaires dans la
     * base de données.
     *
     * @param conn la connexion à la base de données
     * @param prestationId l'identifiant de la prestation à mettre à jour
     * @param partenaireIds la liste des identifiants des partenaires à associer
     * à la prestation
     * @throws SQLException si une erreur survient lors de l'accès ou de la mise
     * à jour dans la base de données
     */
    private void updatePartenaire(Connection conn, int prestationId, List<Integer> partenaireIds) throws SQLException {
        if (partenaireIds != null) {
            String deleteSql = "DELETE FROM proposer WHERE id_prestation=?";
            try (PreparedStatement deleteStmt = conn.prepareStatement(deleteSql)) {
                deleteStmt.setInt(1, prestationId);
                deleteStmt.executeUpdate();
            }
            String insertSql = "INSERT INTO proposer (id_presatation, id_partenaire) VALUES (?, ?)";
            try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                for (int partenaireId : partenaireIds) {
                    insertStmt.setInt(1, prestationId);
                    insertStmt.setInt(2, partenaireId);
                    insertStmt.executeUpdate();
                }
            }
        }
    }

    /**
     * Met à jour les relations entre une prestation et ses collaborateurs dans
     * la base de données.
     *
     * @param conn la connexion à la base de données
     * @param prestationId l'identifiant de la prestation à mettre à jour
     * @param collaborateurIds la liste des identifiants des collaborateurs à
     * associer à la prestation
     * @throws SQLException si une erreur survient lors de l'accès ou de la mise
     * à jour dans la base de données
     */
    private void updateCollaborateur(Connection conn, int prestationId, List<Integer> collaborateurIds) throws SQLException {
        if (collaborateurIds != null) {
            String deleteSql = "DELETE FROM proposer WHERE id_prestation=?";
            try (PreparedStatement deleteStmt = conn.prepareStatement(deleteSql)) {
                deleteStmt.setInt(1, prestationId);
                deleteStmt.executeUpdate();
            }
            String insertSql = "INSERT INTO proposer (id_prestation, id_collaborateur) VALUES (?, ?)";
            try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                for (int collaborateurId : collaborateurIds) {
                    insertStmt.setInt(1, prestationId);
                    insertStmt.setInt(2, collaborateurId);
                    insertStmt.executeUpdate();
                }
            }
        }
    }

    /**
     * Met à jour les relations entre une prestation et ses responsables
     * d'activité dans la base de données.
     *
     * @param conn la connexion à la base de données
     * @param prestationId l'identifiant de la prestation à mettre à jour
     * @param responsableIds la liste des identifiants des responsables
     * d'activité à associer à la prestation
     * @throws SQLException si une erreur survient lors de l'accès ou de la mise
     * à jour dans la base de données
     */
    private void updateResponsablesActivite(Connection conn, int prestationId, List<Integer> responsableIds) throws SQLException {
        if (responsableIds != null) {
            String deleteSql = "DELETE FROM proposer WHERE id_prestation=?";
            try (PreparedStatement deleteStmt = conn.prepareStatement(deleteSql)) {
                deleteStmt.setInt(1, prestationId);
                deleteStmt.executeUpdate();
            }

            String insertSql = "INSERT INTO proposer (id_prestation, id_ra) VALUES (?, ?)";
            try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                for (int responsableId : responsableIds) {
                    insertStmt.setInt(1, prestationId);
                    insertStmt.setInt(2, responsableId);
                    insertStmt.executeUpdate();
                }
            }
        }
    }

    /**
     * Met à jour une prestation dans la base de données avec les nouvelles
     * valeurs spécifiées.
     *
     * @param obj la prestation contenant les nouvelles valeurs à mettre à jour
     */
    @Override
    public void update(Prestation obj) {
        String sql = "UPDATE prestation SET siglum_presta=?, num_affaire=?, nom_presta=?, ref_fact_partenaire=?, mail_partenaire=?,"
                + " ref_fact_airbus=?, mail_airbus=?, id_ra=?, id_collaborateur=?, id_partenaire=? WHERE id_prestation=?";
        String sqlInsertHistorique = "INSERT INTO historique (date_action, action, table_originale, id_element,  ancienne_valeur, nouvelle_valeur) "
                + "VALUES ( ?, ?, ?, ?, ?, ?)";
        try {
            Prestation prestationAvant = read(obj.getId());
            
            
            PreparedStatement pstmt = connexion.prepareStatement(sql);
            pstmt.setString(1, obj.getSiglum_presta());
            pstmt.setString(2, obj.getNum_affaire());
            pstmt.setString(3, obj.getNom_presta());
            pstmt.setString(4, obj.getRef_fact_partenaire());
            pstmt.setString(5, obj.getMail_partenaire());
            pstmt.setString(6, obj.getRef_fact_airbus());
            pstmt.setString(7, obj.getMail_airbus());
            pstmt.setInt(8, obj.getId_ra());
            pstmt.setInt(9, obj.getId_collaborateur());
            pstmt.setInt(10, obj.getId_partenaire());
            pstmt.setInt(11, obj.getId());

            pstmt.executeUpdate();
            
            Prestation prestationApres = read(obj.getId());

            /*updatePartenaire(connexion, obj.getId(), obj.getPartenaireIds());
            updateCollaborateur(connexion, obj.getId(), obj.getCollaborateurIds());
            updateResponsablesActivite(connexion, obj.getId(), obj.getResponsablesIds());*/
            
            
            PreparedStatement pstmtInsertHistorique = connexion.prepareStatement(sqlInsertHistorique);
                 pstmtInsertHistorique.setTimestamp(1, Timestamp.valueOf(LocalDateTime.now()));
            pstmtInsertHistorique.setString(2, "mise à jour");
            
            pstmtInsertHistorique.setString(3, "prestation");
            pstmtInsertHistorique.setInt(4, obj.getId());
            
            
            
                         // Date d'action actuelle

            pstmtInsertHistorique.setString(5, JsonUtil.prestationToJson(prestationAvant)); // Convertir en JSON ou autre format texte
            pstmtInsertHistorique.setString(6, JsonUtil.prestationToJson(prestationApres)); // Convertir en JSON ou autre format texte

            pstmtInsertHistorique.executeUpdate();

                // Journalisation avant et après la modification
                CSVUtil.writeHistory("Modification de prestation", prestationAvant);
                CSVUtil.writeHistory("Après modification", prestationApres);
            
            
        } catch (SQLException ex) {
            System.out.println("Erreur lors de la mise à jour : " + ex.getMessage());
        }
         catch (IOException ex) {
            Logger.getLogger(CollaborateurDao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Supprime une prestation de la base de données en fonction de son
     * identifiant.
     *
     * @param id l'identifiant de la prestation à supprimer
     */
    public void delete(Integer id) throws IOException {
        String sql = "DELETE FROM prestation WHERE id_prestation=?";
        try {
            
            Prestation prestation = read(id);
            
            PreparedStatement pstmt = connexion.prepareStatement(sql);
            pstmt.setInt(1, id);
            pstmt.executeUpdate();
            
            // Enregistrer historique dans la BDD
            String sqlInsertHistorique = "INSERT INTO historique (date_action, action, table_originale, id_element,  ancienne_valeur, nouvelle_valeur) "
                + "VALUES ( ?, ?, ?, ?, ?, ?)";

            PreparedStatement pstmtInsertHistorique = connexion.prepareStatement(sqlInsertHistorique);
                 pstmtInsertHistorique.setTimestamp(1, Timestamp.valueOf(LocalDateTime.now()));
            pstmtInsertHistorique.setString(2, "suppression");
            
            pstmtInsertHistorique.setString(3, "prestation");
            pstmtInsertHistorique.setInt(4, prestation.getId());
            
                         // Date d'action actuelle

            pstmtInsertHistorique.setString(5, prestationToJson(prestation)); // Convertir en JSON ou autre format texte
            pstmtInsertHistorique.setString(6, null); // Convertir en JSON ou autre format texte

            pstmtInsertHistorique.executeUpdate();
            
            
            
            // Enregistrer les informations dans le fichier CSV
            CSVUtil.writeHistory("Avant suppression de prestation", prestation);
            
            
        } catch (SQLException ex) {
            System.out.println("Erreur lors du delete : " + ex.getMessage());
        }
    }

    /**
     * Retourne une collection de prestations à partir du nom spécifié.
     *
     * @param nom_presta le nom de la prestation à rechercher
     * @return une collection de prestations correspondant au nom spécifié
     */
    public Collection<Prestation> listByNom(String nom_presta) {
        ArrayList<Prestation> listNom = new ArrayList<>();
        String sql = "SELECT * FROM " + table + " WHERE nom_presta =?";

        try (
                PreparedStatement pstmt = connexion.prepareStatement(sql)) {
            pstmt.setString(1, nom_presta);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                Prestation obj = createObject(rs);
                listNom.add(obj);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return listNom;
    }

//    @Override
//    public Collection<Prestation> list() {
//        ArrayList<Prestation> list = new ArrayList<>();
//        String sql = "SELECT * FROM prestation";
//        try (PreparedStatement pstmt = connexion.prepareStatement(sql)) {
//
//            ResultSet rs = pstmt.executeQuery();
//            while (rs.next()) {
//                Prestation c = new Prestation();
//                c.setId(rs.getInt("id_prestation"));
//                c.setSiglum_presta(rs.getString("siglum_presta"));
//                c.setNum_affaire(rs.getString("numero_affaire"));
//                c.setNom_presta(rs.getString("nom_presta"));
//                c.setRef_fact_partenaire(rs.getString("ref_fact_partenaire"));
//                c.setMail_partenaire(rs.getString("mail_partenaire"));
//                c.setRef_fact_airbus(rs.getString("ref_fact_airbus"));
//                c.setMail_airbus(rs.getString("mail_airbus"));
//                c.setId_ra(rs.getInt("id_ra"));
//                c.setId_collaborateur(rs.getInt("id_collaborateur"));
//                c.setId_partenaire(rs.getInt("id_partenaire"));
//                list.add(c);
//            }
//        } catch (SQLException ex) {
//            System.err.println("Erreur lors du listage : " + ex.getMessage());
//        }
//        return list;
//    }
    /**
     * Vérifie si une prestation avec le nom spécifié existe dans la base de
     * données.
     *
     * @param nom_presta le nom de la prestation à vérifier
     * @return true si une prestation avec le nom spécifié existe, sinon false
     */
    public boolean exists(String nom_presta) {
        String sql = "SELECT 1 FROM prestation WHERE nom_presta=?";
        try {
            PreparedStatement pstmt = connexion.prepareStatement(sql);
            pstmt.setString(1, nom_presta);
            ResultSet rs = pstmt.executeQuery();
            return rs.next();
        } catch (SQLException ex) {
            System.err.println("Erreur lors de la vérification de l'existence : " + ex.getMessage());
        }
        return false;
    }

    /**
     * Récupère la liste complète de toutes les prestations enregistrées dans la
     * base de données.
     *
     * @return une collection contenant toutes les prestations enregistrées
     */
    public Collection<Prestation> listPrestation() {
        ArrayList<Prestation> list = new ArrayList<>();
        String sql = "SELECT * FROM prestation";
        try (PreparedStatement pstmt = connexion.prepareStatement(sql)) {

            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                Prestation c = new Prestation();
                c.setId(rs.getInt("id_collaborateur"));
                c.setSiglum_presta(rs.getString("singlum_presta"));
                c.setNum_affaire(rs.getString("num_affaire"));
                c.setNom_presta(rs.getString("nom_presta"));
                c.setRef_fact_partenaire(rs.getString("ref_fact_partenaire"));
                c.setMail_partenaire(rs.getString("mail_partenaire"));
                c.setRef_fact_airbus(rs.getString("ref_fact_airbus"));
                c.setMail_airbus(rs.getString("mail_airbus"));
                c.setId_ra(rs.getInt("id_ra"));
                c.setId_collaborateur(rs.getInt("id_collaborateur"));
                c.setId_partenaire(rs.getInt("id_partenaire"));

                list.add(c);
            }

        } catch (SQLException ex) {
            System.err.println("Erreur lors du listage : " + ex.getMessage());
        }
        return list;
    }

    /**
     * Récupère l'identifiant maximum (ID) actuellement enregistré dans la table
     * des prestations.
     *
     * @return l'ID maximum actuellement enregistré dans la table des
     * prestations, ou 0 s'il n'y a pas d'enregistrement
     */
    public int getLastIdCreated() {
        String sql = "SELECT MAX(id_prestation) AS max_id FROM prestation";
        int maxId = 0;
        try (PreparedStatement pstmt = connexion.prepareStatement(sql)) {
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                maxId = rs.getInt("max_id");
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de l'exécution de la requête : " + ex.getMessage());
        }
        return maxId;
    }

    /**
     * Récupère la liste des responsables d'activité associés à une prestation
     * spécifique.
     *
     * @param idPrestation l'identifiant de la prestation pour laquelle
     * récupérer les responsables d'activité
     * @return une collection contenant les responsables d'activité associés à
     * la prestation spécifiée
     */
    public Collection<ResponsableActivite> listPrestationResponsableActivite(int idPrestation) {
        String sql = "SELECT id_ra FROM prestation WHERE id_prestation = ?";
        ArrayList<ResponsableActivite> list = new ArrayList<>();
        try (PreparedStatement pstmt = connexion.prepareStatement(sql)) {
            pstmt.setInt(1, idPrestation);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    int idRa = rs.getInt("id_ra");
                    ResponsableActivite ra = DaoFactory.ResponsableActiviteDao().read(idRa);
                    if (ra != null) {
                        list.add(ra);
                    }
                }
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de la vérification de l'existence : " + ex.getMessage());
        }
        return list;
    }

    /**
     * Récupère la liste des collaborateurs associés à une prestation
     * spécifique.
     *
     * @param idPrestation l'identifiant de la prestation pour laquelle
     * récupérer les collaborateurs
     * @return une collection contenant les collaborateurs associés à la
     * prestation spécifiée
     */
    public Collection<Collaborateur> listPrestationCollaborateur(int idPrestation) {
        String sql = "SELECT id_collaborateur FROM prestation WHERE id_prestation = ?";
        ArrayList<Collaborateur> list = new ArrayList<>();
        try (PreparedStatement pstmt = connexion.prepareStatement(sql)) {
            pstmt.setInt(1, idPrestation);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    int idCollaborateur = rs.getInt("id_collaborateur");
                    Collaborateur collaborateur = DaoFactory.getCollaborateurDao().read(idCollaborateur);
                    if (collaborateur != null) {
                        list.add(collaborateur);
                    }
                }
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de la vérification de l'existence : " + ex.getMessage());
        }
        return list;
    }

    /**
     * Récupère la liste des partenaires associés à une prestation spécifique.
     *
     * @param idPrestation l'identifiant de la prestation pour laquelle
     * récupérer les partenaires
     * @return une collection contenant les partenaires associés à la prestation
     * spécifiée
     */
    public Collection<Partenaire> listPrestationPartenaire(int idPrestation) {
        String sql = "SELECT id_partenaire FROM prestation WHERE id_prestation = ?";
        ArrayList<Partenaire> list = new ArrayList<>();
        try (PreparedStatement pstmt = connexion.prepareStatement(sql)) {
            pstmt.setInt(1, idPrestation);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    int idPartenaire = rs.getInt("id_partenaire");
                    Partenaire partenaire = DaoFactory.getPartenaireDao().read(idPartenaire);
                    if (partenaire != null) {
                        list.add(partenaire);
                    }
                }
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de la vérification de l'existence : " + ex.getMessage());
        }
        return list;
    }

}
