package dao;

import entities.ResponsableActivite;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;

/**
 *
 * @author asolanas
 */
public class ResponsableActiviteDao extends Dao<ResponsableActivite> {

    public ResponsableActiviteDao() {
        super("ra");
    }

    @Override
    protected ResponsableActivite createObject(ResultSet rs) throws SQLException {
        ResponsableActivite ra = new ResponsableActivite() {
        };
        ra.setId(rs.getInt("id_" + table));
        ra.setMatricule(rs.getInt("matricule"));
        ra.setNom(rs.getString("nom"));
        ra.setPrenom(rs.getString("prenom"));
        ra.setTelephone_professionnel(rs.getString("telephone_professionnel"));
        ra.setTelephone_personnel(rs.getString("telephone_personnel"));

        return ra;
    }

    @Override
    public void create(ResponsableActivite ra) throws SQLException {
        String sql = "INSERT INTO ra(matricule, nom, prenom, telephone_professionnel, telephone_personnel) "
                + "VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement pstmt = connexion.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)) {
            pstmt.setInt(1, ra.getMatricule());
            pstmt.setString(2, ra.getNom());
            pstmt.setString(3, ra.getPrenom());
            pstmt.setString(4, ra.getTelephone_professionnel());
            pstmt.setString(5, ra.getTelephone_personnel());
            int nbLines = pstmt.executeUpdate();
            if (nbLines == 1) {
                ResultSet autoGeneratedKeys = pstmt.getGeneratedKeys();
                autoGeneratedKeys.first();
                int id = autoGeneratedKeys.getInt(1);
                ra.setId(id);
                System.out.println("Responsable d'activité créé avec succès!");
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de l'insertion : " + ex.getMessage());
            throw ex;
        }
    }

    @Override
    public ResponsableActivite read(Integer id) {
        ResponsableActivite ra = null;
        String sql = "SELECT * FROM ra WHERE id_ra=?";
        try (PreparedStatement pstmt = connexion.prepareStatement(sql)) {
            System.out.println("Connexion établie : " + (connexion != null));
            pstmt.setInt(1, id);
            System.out.println("Exécution de la requête SQL : " + sql);
            ResultSet rs = pstmt.executeQuery();
            if (rs.first()) {
                ra = new ResponsableActivite();
                ra.setId(rs.getInt("id_ra"));
                ra.setMatricule(rs.getInt("matricule"));
                ra.setNom(rs.getString("nom"));
                ra.setPrenom(rs.getString("prenom"));
                ra.setTelephone_professionnel(rs.getString("telephone_professionnel"));
                ra.setTelephone_personnel(rs.getString("telephone_personnel"));
                System.out.println("ResponsableActivite trouvé : " + ra);
            }
        } catch (Exception e) {
            System.err.println("Erreur lors de la lecture : " + e.getMessage());
            e.printStackTrace(); // Imprimer la pile d'erreurs pour un meilleur débogage
        }
        return ra;
    }
    
     // rajout test
    public boolean exists(int matricule) {
        String sql = "SELECT 1 FROM ra WHERE matricule=?";
        try {
            PreparedStatement pstmt = connexion.prepareStatement(sql);
            pstmt.setInt(1, matricule);
            ResultSet rs = pstmt.executeQuery();
            return rs.next();
        } catch (SQLException ex) {
            System.err.println("Erreur lors de la vérification de l'existence : " + ex.getMessage());
        }
        return false;
    }

    @Override
    protected void update(ResponsableActivite obj) {
    }

}
